FROM python:3.8

WORKDIR /app

COPY requirements.txt .
RUN ["pip", "install", "-r", "requirements.txt"]

# COPY . .
COPY run.py .

# CMD ["python", "-m", "http.server", "5000"]
CMD ["flask", "run", "--host", "0.0.0.0"]