version: "3.0"
services: 
  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports: 
      - "8080:8080"
    volumes:
      - ./app:/app/app
      - ./public:/app/public
      - ./src:/app/src
      - ./dist:/app/dist
      - ./.yarn-cache:/app/.yarn-cache
    # command: ["./app/run_client.sh"]
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app/app
      - ./public:/app/public
      - ./src:/app/src
      - ./dist:/app/dist
    # command: ["./app/run_server.py"]
